// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvZH2DCvRc6vmDLM4yM8IauJk6MH0FWaM',
    appId: '1:279595651002:web:077cbebe933b57ac205783',
    messagingSenderId: '279595651002',
    projectId: 'ai-story-generation-5e628',
    authDomain: 'ai-story-generation-5e628.firebaseapp.com',
    storageBucket: 'ai-story-generation-5e628.firebasestorage.app',
    measurementId: 'G-Y75Z0JJ75T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJydhnLoJI5o_oZPtqjTiytDKubUnyilM',
    appId: '1:279595651002:android:77193e3acf6df04d205783',
    messagingSenderId: '279595651002',
    projectId: 'ai-story-generation-5e628',
    storageBucket: 'ai-story-generation-5e628.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEiKtWDGoMlh3pENsfn-5Tl3Zg_ScHJmg',
    appId: '1:279595651002:ios:322078b11a634548205783',
    messagingSenderId: '279595651002',
    projectId: 'ai-story-generation-5e628',
    storageBucket: 'ai-story-generation-5e628.firebasestorage.app',
    iosBundleId: 'com.example.aiStoryGen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEiKtWDGoMlh3pENsfn-5Tl3Zg_ScHJmg',
    appId: '1:279595651002:ios:322078b11a634548205783',
    messagingSenderId: '279595651002',
    projectId: 'ai-story-generation-5e628',
    storageBucket: 'ai-story-generation-5e628.firebasestorage.app',
    iosBundleId: 'com.example.aiStoryGen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvZH2DCvRc6vmDLM4yM8IauJk6MH0FWaM',
    appId: '1:279595651002:web:a2e5a9620e29907a205783',
    messagingSenderId: '279595651002',
    projectId: 'ai-story-generation-5e628',
    authDomain: 'ai-story-generation-5e628.firebaseapp.com',
    storageBucket: 'ai-story-generation-5e628.firebasestorage.app',
    measurementId: 'G-BTSXLP2BHS',
  );
}
