// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZHaPDy15NMBhIKqNU5qDdEsOmPG1ox98',
    appId: '1:391779423473:web:5d70bc2fbc7e1f147d4550',
    messagingSenderId: '391779423473',
    projectId: 'ai-story-gen',
    authDomain: 'ai-story-gen.firebaseapp.com',
    storageBucket: 'ai-story-gen.firebasestorage.app',
    measurementId: 'G-0RT5T88SSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtZgDv6lmBEG0sCmbNqkvzbkO4cHiPtrM',
    appId: '1:391779423473:android:d8c19c661ab2246d7d4550',
    messagingSenderId: '391779423473',
    projectId: 'ai-story-gen',
    storageBucket: 'ai-story-gen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqQjqm6pTtEnrLTYSVvyzt-AxUhAiLc_E',
    appId: '1:391779423473:ios:5043c8099648cc407d4550',
    messagingSenderId: '391779423473',
    projectId: 'ai-story-gen',
    storageBucket: 'ai-story-gen.firebasestorage.app',
    iosBundleId: 'com.example.aiStoryGen',
  );
}
